/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class token_stream_TokenFileReader */

#ifndef _Included_token_stream_TokenFileReader
#define _Included_token_stream_TokenFileReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     token_stream_TokenFileReader
 * Method:    read0
 * Signature: (Ljava/lang/String;)[C
 */
JNIEXPORT jcharArray JNICALL Java_token_1stream_TokenFileReader_read0
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
